import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import TransitionEffect from "./TransitionEffects";
import { ColorModeContext } from "@/contexts/ColorModeContext";
import ConfigComponent from "./ConfigComponent";
import { AuthContextProvider } from "@/contexts/AuthContext";
import AuthorizedAlert from "./ToastAlert";
import ToastAlertContext from "@/contexts/ToastAlertContext";
import favicon from "./favicon.ico";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Open Hearts",
    description: "Generated by create next app",
    icons: [
        {
            url: favicon.src,
            sizes: "32x32",
            type: "image/x-icon",
        },
    ],
};

export default function RootLayout({
    children,
}: {
    children: React.ReactElement;
}) {
    return (
        <html lang="en" className="doodle">
            <body className={font.className}>
                <ColorModeContext>
                    <ToastAlertContext>
                        <ConfigComponent />
                        <TransitionEffect>
                            <AuthContextProvider>
                                {children}
                                <AuthorizedAlert />
                            </AuthContextProvider>
                        </TransitionEffect>
                    </ToastAlertContext>
                </ColorModeContext>
            </body>
        </html>
    );
}
