import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import TransitionEffect from "./TransitionEffects";
import { ColorModeContext } from "@/contexts/ColorModeContext";
import ConfigComponent from "./ConfigComponent";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Open Hearts",
    description: "Generated by create next app",
    icons: [
        {
            url: "/favicon.ico",
            sizes: "32x32",
            type: "image/x-icon",
        },
    ],
};

export default function RootLayout({
    children,
}: {
    children: React.ReactElement;
}) {
    return (
        <html lang="en">
            <body className={montserrat.className}>
                <ColorModeContext>
                    <>
                        <ConfigComponent />
                        <TransitionEffect>{children}</TransitionEffect>
                    </>
                </ColorModeContext>
            </body>
        </html>
    );
}
