import "./globals.css";
import type { Metadata } from "next";
import ThemeControl from "@/contexts/ThemeControl";
import { Montserrat } from "next/font/google";
import TransitionEffect from "./TransitionEffects";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: [
        {
            url: "/favicon.ico",
            sizes: "32x32",
            type: "image/x-icon",
        },
    ],
};

export default function RootLayout({
    children,
}: {
    children: React.ReactElement;
}) {
    return (
        <html lang="en">
            <ThemeControl>
                <body className={inter.className}>
                    <TransitionEffect>
                        {children}
                    </TransitionEffect>
                </body>
            </ThemeControl>
        </html>
    );
}
