name: Remove need-attention and add started-working labels

on:
    push:
        branches:
            - issues/**

jobs:
    update-labels:
        runs-on: ubuntu-latest

        steps:
            - name: Remove need-attention label
              uses: actions/github-script@v6
              with:
                  script: |
                      github.issues.removeLabel({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        label: "need-attention"
                      })

            - name: Add started-working label
              uses: actions/github-script@v6
              with:
                  script: |
                      github.issues.addLabels({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        labels: ["started-working"]
                      })
